"""
plot_country_metrics.py — per-country performance charts for static inference and nowcast.

Reads the metrics_per_country.csv files already generated by static_inference.py and
nowcast.py and produces horizontal dot-plot figures, one per round.

Run: C:/Users/jonas/miniconda3/envs/ewm/python.exe hero_v6/ML/codes/plot_country_metrics.py
"""

import os
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("MKL_THREADING_LAYER", "SEQUENTIAL")

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.lines as mlines

ROOT   = Path(__file__).resolve().parents[2]
SI_DIR = ROOT / "ML" / "results" / "static_inference"
NC_DIR = ROOT / "ML" / "results" / "nowcast"

# ----------------------------------------------------------------- style
MODEL_STYLE = {
    "xgboost":              {"color": "#0077b6", "marker": "o", "label": "XGBoost",      "zorder": 4},
    "random_forest":        {"color": "#2d9e6b", "marker": "s", "label": "RandomForest", "zorder": 3},
    "lightgbm":             {"color": "#e07b39", "marker": "^", "label": "LightGBM",     "zorder": 3},
    "persistence":          {"color": "#888888", "marker": "D", "label": "Persistence",  "zorder": 2},
    "baseline_country_mean":{"color": "#888888", "marker": "D", "label": "Country mean", "zorder": 2},
}
CLIP = (-1.0, 1.0)   # R² values clipped for display (extreme negatives compress the axis)


def dot_chart(ax, df_pivot, models, sort_col, clip=CLIP, xlabel="R²"):
    """
    Horizontal dot chart: countries on y-axis, metric on x-axis.
    df_pivot: index=Country, columns=models.
    sort_col: column to sort countries by (descending).
    """
    order = df_pivot[sort_col].sort_values(ascending=True).index   # ascending so best is at top
    n = len(order)

    # grey horizontal grid lines
    ax.set_yticks(range(n))
    ax.set_yticklabels(order, fontsize=7.5)
    ax.yaxis.set_tick_params(length=0)
    ax.grid(axis="x", lw=0.4, alpha=0.5, zorder=0)
    ax.axvline(0, color="#333333", lw=0.8, zorder=1)

    for i, ctry in enumerate(order):
        # faint horizontal rule
        ax.axhline(i, color="#eeeeee", lw=0.6, zorder=0)
        for model in models:
            if model not in df_pivot.columns:
                continue
            val = df_pivot.loc[ctry, model]
            if pd.isna(val):
                continue
            clipped = np.clip(val, *clip)
            st = MODEL_STYLE[model]
            kw = dict(color=st["color"], marker=st["marker"], zorder=st["zorder"],
                      markersize=5, markeredgewidth=0.4, markeredgecolor="white",
                      linestyle="none")
            ax.plot(clipped, i, **kw)
            # arrow if clipped
            if val < clip[0]:
                ax.annotate("", xy=(clip[0] + 0.02, i), xytext=(clip[0] + 0.06, i),
                            arrowprops=dict(arrowstyle="<-", color=st["color"], lw=1.0))

    ax.set_xlim(clip[0] - 0.08, clip[1] + 0.05)
    ax.set_ylim(-0.8, n - 0.2)
    ax.set_xlabel(xlabel, fontsize=9)
    ax.spines[["top", "right", "left"]].set_visible(False)


def make_legend(models, loc="lower right"):
    return [mlines.Line2D([], [], color=MODEL_STYLE[m]["color"],
                          marker=MODEL_STYLE[m]["marker"], linestyle="none",
                          markersize=5, label=MODEL_STYLE[m]["label"])
            for m in models if m in MODEL_STYLE]


# ================================================================= STATIC INFERENCE
def plot_static(path_in, path_out):
    df = pd.read_csv(path_in)
    models = ["xgboost", "random_forest", "lightgbm", "baseline_country_mean"]

    piv_r2  = df.pivot_table(index="Country", columns="model", values="R2")
    piv_mae = df.pivot_table(index="Country", columns="model", values="MAE")

    # countries that appear in both
    countries = piv_r2.index[piv_r2["xgboost"].notna()]
    piv_r2  = piv_r2.loc[countries]
    piv_mae = piv_mae.loc[countries]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, max(8, len(countries) * 0.28)),
                                    sharey=True)
    dot_chart(ax1, piv_r2,  models, sort_col="xgboost", xlabel="R²  (clipped at −1)")
    dot_chart(ax2, piv_mae, models, sort_col="xgboost",
              clip=(0, piv_mae["xgboost"].quantile(0.95) * 1.1),
              xlabel="MAE (pp)")
    ax2.set_xlim(0, piv_mae["xgboost"].quantile(0.95) * 1.1)

    ax1.set_title("R²", fontsize=9, pad=4)
    ax2.set_title("MAE (percentage points)", fontsize=9, pad=4)

    handles = make_legend(models)
    fig.legend(handles=handles, loc="lower center", ncol=len(models),
               fontsize=8, frameon=True, framealpha=0.9, bbox_to_anchor=(0.5, -0.01))
    fig.suptitle("Static inference — per-country performance (geographic hold-out)",
                 fontsize=10, fontweight="bold")
    fig.tight_layout(rect=[0, 0.04, 1, 0.97])
    fig.savefig(path_out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {path_out.name}")


# ================================================================= NOWCAST
def plot_nowcast(path_in, path_out):
    df = pd.read_csv(path_in)
    # keep only the nowcast feature set and persistence
    df_nc   = df[df["feature_set"] == "nowcast"]
    df_pers = df[df["feature_set"] == "-"]
    df_plot = pd.concat([df_nc, df_pers], ignore_index=True)

    models = ["xgboost", "random_forest", "lightgbm", "persistence"]

    piv_r2  = df_plot.pivot_table(index="Country", columns="model", values="R2")
    piv_mae = df_plot.pivot_table(index="Country", columns="model", values="MAE")

    countries = piv_r2.index[piv_r2["xgboost"].notna()]
    piv_r2  = piv_r2.loc[countries]
    piv_mae = piv_mae.loc[countries]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, max(8, len(countries) * 0.28)),
                                    sharey=True)
    dot_chart(ax1, piv_r2,  models, sort_col="xgboost", xlabel="R²  (clipped at −1)")
    dot_chart(ax2, piv_mae, models, sort_col="xgboost",
              clip=(0, piv_mae["xgboost"].quantile(0.95) * 1.1),
              xlabel="MAE (pp)")
    ax2.set_xlim(0, piv_mae["xgboost"].quantile(0.95) * 1.1)

    ax1.set_title("R²", fontsize=9, pad=4)
    ax2.set_title("MAE (percentage points)", fontsize=9, pad=4)

    handles = make_legend(models)
    fig.legend(handles=handles, loc="lower center", ncol=len(models),
               fontsize=8, frameon=True, framealpha=0.9, bbox_to_anchor=(0.5, -0.01))
    fig.suptitle("Nowcast — per-country performance (train_all | eval_current, nowcast feature set)",
                 fontsize=10, fontweight="bold")
    fig.tight_layout(rect=[0, 0.04, 1, 0.97])
    fig.savefig(path_out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {path_out.name}")


# ================================================================= main
if __name__ == "__main__":
    si_csv = SI_DIR / "metrics_per_country.csv"
    nc_csv = NC_DIR / "metrics_per_country.csv"

    if si_csv.exists():
        plot_static(si_csv, SI_DIR / "per_country_performance.png")
    else:
        print(f"Missing: {si_csv} — run static_inference.py first")

    if nc_csv.exists():
        plot_nowcast(nc_csv, NC_DIR / "per_country_performance.png")
    else:
        print(f"Missing: {nc_csv} — run nowcast.py first")
